---
title: Scott Klein
tagline: Byte shepherd. Fumbling founder.
name: Scott Klein
twitter: scootklein
github: scootklein
email: scott@klein.io
google_analytics_id: UA-21155180-1
login: <%= ENV['OBTVSE_LOGIN'] %>
password: <%= ENV['OBTVSE_PASSWORD'] %>
